### GET all holiday of all employees (without limit)
GET http://localhost:8080/api/holiday
Accept: application/json
Content-Type: application/json
Authorization: Basic w.runninggoat@aol.us HelloWorld!

### GET holiday filtering on emails
GET http://localhost:8080/api/holiday?email=m.bouvier@aol.us&email=l.bouvier@aol.us
Accept: application/json
Content-Type: application/json
Authorization: Basic w.runninggoat@aol.us HelloWorld!

### GET holiday filtering on email and year
GET http://localhost:8080/api/holiday?email=c.ehtridge@aol.us&year=2020
Accept: application/json
Content-Type: application/json
Authorization: Basic w.runninggoat@aol.us HelloWorld!

### a DEVELOPER employee add a day off for someone
POST http://localhost:8080/api/holiday
Accept: application/json
Content-Type: application/json
Authorization: Basic c.ehtridge@aol.us HelloWorld!

{
  "employee_email": "c.ehtridge@aol.us",
  "day_off": "2020-06-22"
}

### Modify a day off to another one for employee
PUT http://localhost:8080/api/holiday
Accept: application/json
Content-Type: application/json
Authorization: Basic c.ehtridge@aol.us HelloWorld!

{
  "employee_email": "c.ehtridge@aol.us",
  "previous_day_off": "2020-06-22",
  "new_day_off": "2020-06-21"
}

### Remove day off for employee
DELETE http://localhost:8080/api/holiday
Accept: application/json
Content-Type: application/json
Authorization: Basic c.ehtridge@aol.us HelloWorld!

{
  "employee_email": "c.ehtridge@aol.us",
  "day_off": "2020-06-22"
}

